name: daily-refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4 * * *'

jobs:
  test-actions:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
      
      - name: Install packages
        run: |
          install.packages("tidyverse")
          install.packages("readxl")
          install.packages("magrittr")
          install.packages("lubridate")
        shell: Rscript {0}
          
      - name: Scrape files
        run: |
          source("R/3_mwmi_data_create.R")
          source("R/4_qpses_mwmi_data_match.R")
        shell: Rscript {0}
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "run daily scrape"
          git push
